// GENERATED by tool/update_version.dart from pubspec.yaml — do not edit by hand.
// Run `dart run tool/update_version.dart` (release.sh / CI do this) to refresh.
//
// kAppVersion is the semantic version shown in the Update Center and compared
// against GitHub releases; kBuildNumber is the +N build (Android versionCode).

const String kAppVersion = '1.2.7';
const int kBuildNumber = 275;
